---
title: "About Me"
---

## 

Here is a little bit about me!

### **Academic Background**

I am currently finishing up my third year in the Statistics major and Computer Science minor at University of Toronto. My interests lie in the intersection of software development, human computer interaction and machine learning. As someone driven by passion for innovation, in the future I plan to be involved within ML and Software Developement opportunities that positively impact users and society in the new era of Aritificial Intelligence.

### **Experiences and Interests**

Throughout the course of my university journey, I've had many learning opportunities to explore data analysis, statistics, and computer science topics in detail and build foundational knowledge in each. As I head into my final year, I am excited to apply these ideas topics towards real machine learning and statistics topics! In the meantime, you can explore some of the projects I have been involved with at [Projects](projects.qmd)

Last summer, I interned at CIBC as a Software Developer Intern where I gained invaluable hands-on experience in the industry developing a mobile application for the bank. I was able to gain a plethora of end-to-end software developing skills, and mastered several skils like Android Studio, Kotlin and Software Design.

### **My Resume**

Here is my resume for a closer look at my skills and experience! Resume: [Download Resume](https://github.com/hoodanav/personal_website/raw/main/Personal-Website-main/Navya_Hooda_Resume_Final.pdf)

### **Relevant Coursework**

During my time at University of Toronto, I have been able to take some exciting and useful courses that set up my interests in the field of Software and Machine Learning, here are a few notable ones:

\
1. STA302 - Methods of Data Analysis I\
2. CSC311 - Introduction to Machine Learning\
3. CSC207 - Software Design Principles\
4. CSC263 - Data Structures and Algorithms\
5. STA258 & STA260 - Probability and Statistics I & \|\|\
